<script setup>
import { reactive,ref,onBeforeUnmount } from 'vue';
import { account } from '../account.js';
import { roles,studio } from '../store.js';
import Avatar from '../components/Avatar.vue';
const form=reactive({...account.state.value}),error=ref(''),message=ref(''),fileInput=ref(),dialog=ref(),cropCanvas=ref(),zoom=ref(1),offset=reactive({x:0,y:0}),cropError=ref(''),loading=ref(false);
let photo=null,url='',drag=null;
function draw(){if(!photo||!cropCanvas.value)return;const ctx=cropCanvas.value.getContext('2d'),size=300,scale=Math.max(size/photo.width,size/photo.height)*zoom.value;const w=photo.width*scale,h=photo.height*scale;offset.x=Math.max(-(w-size)/2,Math.min((w-size)/2,offset.x));offset.y=Math.max(-(h-size)/2,Math.min((h-size)/2,offset.y));ctx.clearRect(0,0,size,size);ctx.fillStyle='#edf0df';ctx.fillRect(0,0,size,size);ctx.drawImage(photo,(size-w)/2+offset.x,(size-h)/2+offset.y,w,h)}
async function choose(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;error.value='';if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){error.value='请选择不超过 2MB 的 JPG、PNG 或 WebP 图片。';return}loading.value=true;try{if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);photo=new Image();photo.src=url;await photo.decode();if(photo.width<64||photo.height<64)throw Error('图片至少需要 64×64 像素。');zoom.value=1;offset.x=offset.y=0;cropError.value='';dialog.value.showModal();draw()}catch(e){error.value=e.message||'图片读取失败，请换一张图片。'}finally{loading.value=false}}
function down(e){e.currentTarget.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y}}
function move(e){if(!drag)return;const ratio=300/e.currentTarget.getBoundingClientRect().width;offset.x=drag.ox+(e.clientX-drag.x)*ratio;offset.y=drag.oy+(e.clientY-drag.y)*ratio;draw()}
function key(e){const delta={ArrowLeft:[-8,0],ArrowRight:[8,0],ArrowUp:[0,-8],ArrowDown:[0,8]}[e.key];if(delta){e.preventDefault();offset.x+=delta[0];offset.y+=delta[1];draw()}}
function saveAvatar(){try{account.call('update',{avatar:cropCanvas.value.toDataURL('image/jpeg',.88)});dialog.value.close();message.value='头像已保存，所有页面已同步。'}catch(e){cropError.value=e.message}}
function resetAvatar(){try{account.call('update',{avatar:''});message.value='已恢复默认头像。'}catch(e){error.value=e.message}}
function save(){try{account.call('update',{nickname:form.nickname,roleId:form.roleId,level:form.level,graduation:form.graduation});studio.call('setPreference',form.roleId);message.value='资料已保存。';error.value=''}catch(e){error.value=e.message}}
onBeforeUnmount(()=>{if(url)URL.revokeObjectURL(url)});
</script>
<template><div class="page-heading profile-heading"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h1>让面试精灵，更了解你。</h1><p class="muted">我的资料，用于当前浏览器的个性化练习。</p></div><RouterLink to="/settings/demo" class="text-link">账户与数据设置 →</RouterLink></div><section class="card profile-card"><h2>头像</h2><div class="profile-photo-row"><Avatar :size="112"/><div><input ref="fileInput" type="file" accept="image/png,image/jpeg,image/webp" hidden @change="choose"/><button class="button primary" :disabled="loading" @click="fileInput.click()">{{loading?'正在读取…':'更换头像'}}</button><button class="text-link reset-avatar" @click="resetAvatar">恢复默认</button><p class="small muted">支持 JPG / PNG / WebP，最大 2MB</p></div></div><hr/><form @submit.prevent="save"><h2>个人信息</h2><label>昵称<input v-model="form.nickname" maxlength="20" required/></label><label>目标岗位<select v-model="form.roleId"><option v-for="r in roles" :key="r.id" :value="r.id">{{r.title}}</option></select></label><div class="form-row"><label>求职阶段<select v-model="form.level"><option>校招</option><option>初级</option><option>中级</option></select></label><label>毕业年份<select v-model="form.graduation"><option v-for="year in ['2024','2025','2026','2027','2028','2029','2030']" :key="year">{{year}}</option></select></label></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="message" class="notice" role="status">{{message}}</p><button class="button primary">保存资料</button></form></section><dialog ref="dialog" class="avatar-dialog"><h2>调整头像</h2><p class="muted small">拖动图片调整位置，也可用方向键移动。</p><div class="crop-frame"><canvas ref="cropCanvas" width="300" height="300" tabindex="0" aria-label="头像裁剪区域，使用方向键移动" @pointerdown="down" @pointermove="move" @pointerup="drag=null" @pointercancel="drag=null" @keydown="key"/><div class="crop-mask"></div></div><label>缩放<input v-model="zoom" type="range" min="1" max="3" step="0.01" @input="draw"/></label><p v-if="cropError" class="error" role="alert">{{cropError}}</p><div class="action-bar"><button class="button secondary" @click="dialog.close()">取消</button><button class="button primary" @click="saveAvatar">保存头像</button></div></dialog></template>
