<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { realRequest } from '../services/real.js';
import ResumeRewrite from '../components/ResumeRewrite.vue';
const route=useRoute(),router=useRouter();
const profile=ref(null),rows=ref([]),selected=ref(null),error=ref(''),notice=ref(''),busy=ref(false),loading=ref(true),consent=ref(false);
const fileInput=ref(null);
const sections=computed(()=>{const groups=new Map();for(const fragment of selected.value?.fragments||[]){const name=fragment.section||'其他';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(fragment);}return [...groups].map(([name,items])=>({name,items}));});
const newest=computed(()=>[...rows.value].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]);
const stateClass=status=>({parsing:'busy',review:'ready',confirmed:'completed',failed:'failed'}[status]||'');
const states={parsing:'解析切割中',review:'待确认',confirmed:'已确认',failed:'解析失败'};
let timer,closed=false;
function reset(){profile.value=null;rows.value=[];selected.value=null;clearTimeout(timer);}
async function perform(fn){busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){error.value=e.message;if(e.status===401){reset();await router.replace({path:'/login',query:{returnTo:route.fullPath}});}}finally{busy.value=false;}}
async function list(){rows.value=await realRequest('/resumes');}
function schedule(){clearTimeout(timer);if(!closed && (selected.value?.status==='parsing'||rows.value.some(r=>r.status==='parsing')))timer=setTimeout(poll,2000);}
async function poll(){try{await list();if(selected.value?.status==='parsing')selected.value=await realRequest(`/resumes/${selected.value.id}`);}catch(e){error.value=e.message;if(e.status===401){reset();await router.replace({path:'/login',query:{returnTo:route.fullPath}});}return;}schedule();}
async function open(id){selected.value=await realRequest(`/resumes/${id}`);await router.replace({path:'/resumes/real',query:{id}});schedule();}
async function initialize(){profile.value=await realRequest('/me');await list();if(route.query.id)await open(route.query.id);schedule();}
async function upload(event){const file=event.target.files[0];event.target.value='';if(!file)return;await perform(async()=>{if(!consent.value)throw Error('请先确认简历处理说明');if(!/\.(pdf|docx)$/i.test(file.name))throw Error('请选择 PDF 或 DOCX 简历');if(file.size>10*1024*1024)throw Error('文件超过 10MB，请压缩后上传');const data=new FormData();data.append('file',file);const result=await realRequest('/resumes',{method:'POST',body:data});await list();await open(result.id);notice.value='原文件已保存，解析状态会自动更新。';});}
async function save(confirm=false){await perform(async()=>{selected.value=await realRequest(`/resumes/${selected.value.id}${confirm?'/confirm':''}`,{method:confirm?'POST':'PUT',body:{revision:selected.value.revision,fragments:selected.value.fragments}});await list();notice.value=confirm?'版本已确认并入库，可使用此版本开始 WB 面试。':'修正已保存。';});}
async function download(){await perform(async()=>{const blob=await realRequest(`/resumes/${selected.value.id}/file`,{binary:true});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=selected.value.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
onMounted(async()=>{try{await initialize();}catch(e){if(e.status!==401)error.value=e.message;else {reset();await router.replace({path:'/login',query:{returnTo:route.fullPath}});}}finally{loading.value=false;}});
onUnmounted(()=>{closed=true;clearTimeout(timer);});
</script>
<template>
  <div class="page-heading"><div><p class="eyebrow">YOUR RESUME, YOUR STORY</p><h1>让每一段经历，清晰可见。</h1><p class="muted">文件与确认版本保存在账户中，随时继续准备。</p></div><RouterLink class="button secondary" to="/interviews/real">准备面试</RouterLink></div>
  <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p>
  <section v-if="loading" class="card">正在读取你的简历…</section>
  <p v-else-if="!profile" class="notice">请先 <RouterLink :to="{path:'/login',query:{returnTo:route.fullPath}}">登录账户</RouterLink>。</p>
  <template v-else>
    <div class="real-resume-grid"><aside class="stack"><section class="card resume-upload"><div class="upload-zone"><span class="upload-symbol" aria-hidden="true">↑</span><h2>上传你的简历</h2><p class="muted">PDF / DOCX · 最大 10MB</p><input ref="fileInput" type="file" accept=".pdf,.docx" hidden :disabled="busy||!consent" @change="upload"/><button type="button" class="button primary" :disabled="busy||!consent" @click="fileInput.click()">{{busy?'正在处理…':'选择简历文件'}}</button></div><label class="check-label"><input type="checkbox" v-model="consent" :disabled="busy"/>同意保存并解析本次简历，解析过程中可能调用已配置的模型服务。</label><p class="small muted">上传 → 解析 → 核对确认 → 开始面试</p></section><section class="card"><div class="section-heading"><h2>我的简历</h2><span class="small muted">{{rows.length}} 份</span><button class="text-link" :disabled="busy" @click="perform(async()=>{await list();schedule();})">刷新</button></div><p v-if="!rows.length" class="muted">还没有简历，上传后会显示在这里。</p><button v-for="row in rows" :key="row.id" class="real-resume-item" :class="{selected:selected?.id===row.id}" :disabled="busy" @click="perform(()=>open(row.id))"><strong>{{row.filename}}</strong><span class="status-badge" :class="'status-'+stateClass(row.status)">{{states[row.status]}}</span><small>{{new Date(row.created_at).toLocaleString()}}</small></button></section></aside>
    <section class="card resume-detail" v-if="selected"><span class="status-badge" :class="'status-'+stateClass(selected.status)">{{states[selected.status]}}</span><h2>{{selected.filename}}</h2><details class="version-details"><summary>版本与原文信息</summary><p class="small muted">版本 {{selected.id.slice(0,8)}} · 修订号 {{selected.revision}}</p><pre class="real-raw">{{selected.raw_text||'原文尚未生成'}}</pre></details><button class="text-link" :disabled="busy" @click="download">下载原文件</button><p v-if="selected.status==='parsing'" class="notice">原文件已入库，正在解析和切割。可以离开页面，稍后回来查看。</p><div v-if="selected.status==='failed'"><p class="error">{{selected.error_message}}</p><button class="button secondary" :disabled="busy" @click="perform(async()=>{await realRequest(`/resumes/${selected.id}/retry`,{method:'POST'});await open(selected.id);await list();})">重试解析</button></div>
      <template v-if="['review','confirmed'].includes(selected.status)"><p v-if="selected.error_message" class="notice" role="status">{{selected.error_message}}</p><div class="resume-sections"><span v-for="group in sections" :key="group.name">{{group.name}} {{group.items.length}}</span></div><p v-if="selected.status==='review'" class="notice">解析完成，请核对章节与内容后确认。你可以先保存修正。</p><div v-if="selected.status==='confirmed'" class="resume-reading"><section v-for="group in sections" :key="group.name"><h3>{{group.name}}</h3><article v-for="fragment in group.items" :key="fragment.id"><p class="preserve">{{fragment.text}}</p><details><summary>原文位置</summary><small>字符 {{fragment.start}}–{{fragment.end}}</small></details></article></section></div><div v-if="selected.status==='review'"><article v-for="(fragment,index) in selected.fragments" :key="fragment.id" class="real-fragment"><div class="form-row"><label>片段 {{index+1}} 章节<select v-model="fragment.section" :disabled="selected.status==='confirmed'||busy"><option v-for="section in ['项目','实习','工作','教育','技能','其他']" :key="section">{{section}}</option></select></label><span class="small muted">原文字符 {{fragment.start}}–{{fragment.end}}</span></div><label>片段 {{index+1}} 内容<textarea v-model="fragment.text" rows="6" maxlength="10000" :readonly="selected.status==='confirmed'" :disabled="busy"/></label></article></div>
      <ResumeRewrite v-if="selected.status==='confirmed'" :key="selected.id" :resume="selected" :role="profile.roleId" @busy="busy=$event" @saved="result=>perform(async()=>{await list();await open(result.id);notice='优化内容已保存为新版本，请核对后确认入库。';})"/><div class="action-bar" v-if="selected.status==='review'"><button class="button secondary" :disabled="busy" @click="save(false)">保存修正</button><button class="button primary" :disabled="busy" @click="save(true)">确认版本并入库</button></div><div v-else><p class="notice">已确认。这个版本将保留，修改请创建新版本。面试将依据已确认内容进行提问。</p><button class="button secondary" :disabled="busy" @click="perform(async()=>{const next=await realRequest(`/resumes/${selected.id}/versions`,{method:'POST'});await list();await open(next.id);})">创建修订版本</button><RouterLink class="button primary" :to="{path:'/interviews/real',query:{resumeId:selected.id}}">使用这份简历开始面试</RouterLink></div></template>
    </section><section class="card empty resume-empty" v-else><span class="upload-symbol" aria-hidden="true">≡</span><h2>{{rows.length?'选择一份简历':'从一份简历开始'}}</h2><p>{{rows.length?'查看解析内容，核对经历，为定向面试做好准备。':'上传简历后，我们会整理教育、技能和项目经历，供你核对。'}}</p><button v-if="newest" class="button secondary" :disabled="busy" @click="perform(()=>open(newest.id))">打开最近简历</button><p v-else class="small muted">请先阅读并勾选左侧处理说明，再选择文件。</p></section></div>
  </template>
</template>
<style scoped>
.real-login{max-width:540px}.real-login label{margin:18px 0}.real-login .text-link{display:block;margin-top:16px}.real-resume-grid{display:grid;grid-template-columns:minmax(270px,.35fr) minmax(0,.65fr);gap:24px;margin-top:24px}.real-resume-item{display:block;width:100%;text-align:left;background:transparent;border:1px solid #dedfd5;border-radius:12px;padding:14px;margin-top:12px;overflow-wrap:anywhere}.real-resume-item.selected{background:#f8efcf;border-color:#d8b251}.real-resume-item small{display:block;margin-top:8px}.real-profile{display:flex;gap:16px;align-items:center;padding:16px 0}.real-profile img{border-radius:50%}.real-raw{white-space:pre-wrap;overflow-wrap:anywhere;max-height:380px;overflow:auto;font:inherit}.real-fragment{padding:18px 0;border-bottom:1px solid #e5e5dc}details{margin-top:18px}summary{cursor:pointer;min-height:44px;padding:10px 0}input[type=file]{max-width:100%}.check-label{margin-bottom:16px}@media(max-width:1000px){.real-resume-grid{grid-template-columns:1fr}.real-profile{flex-wrap:wrap}.section-heading{flex-wrap:wrap;gap:12px}.section-heading .button{white-space:nowrap}}
.account-summary{padding:18px 24px}.account-summary .section-heading{margin-bottom:0}.account-summary h2{font-size:16px}.account-summary p{font-size:12px}.upload-zone{text-align:center;border:1px dashed #bdc9ac;background:#f7f9f1;border-radius:12px;padding:24px 14px}.upload-symbol{display:block;font-size:32px;color:#687b51;line-height:1.4;margin-bottom:12px}.resume-upload .check-label{font-size:12px;align-items:flex-start}.resume-upload input[hidden]{display:none}.resume-empty{min-height:360px;display:flex;flex-direction:column;align-items:center;justify-content:center}.resume-empty p{max-width:350px}.resume-detail>h2{margin-top:12px;overflow-wrap:anywhere}.resume-sections{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.resume-sections span{background:#eef2e8;color:#526249;border-radius:7px;padding:5px 10px;font-size:12px}.resume-reading>section{padding:20px 0;border-bottom:1px solid var(--line)}.resume-reading h3{border-left:3px solid var(--gold);padding-left:12px}.resume-reading article{margin-top:14px}.resume-reading p{line-height:1.9}.resume-reading summary,.version-details summary{font-size:12px;color:var(--muted)}.real-resume-item .status-badge{margin-top:8px}.resume-detail>.status-badge{margin-bottom:8px}@media(max-width:767px){.resume-empty{min-height:240px}.resume-detail .button{width:100%;margin-top:10px}.real-resume-grid{gap:16px}.account-summary{padding:16px}}
</style>
