<script setup>
import { ref, reactive, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { realRequest, clearRealSession } from '../services/real.js';
import { clearAccount } from '../services/realAccount.js';
const route=useRoute(),router=useRouter(),reset=computed(()=>route.path==='/forgot-password');
const form=reactive({phone:'',nickname:'',email:'',password:'',confirm:'',code:''});
const challenge=ref(''),sentEmail=ref(''),busy=ref(false),error=ref(''),notice=ref('');
async function send(){busy.value=true;error.value='';notice.value='';challenge.value='';try{const result=await realRequest(`/auth/${reset.value?'reset':'register'}/code`,{method:'POST',body:{email:form.email}});challenge.value=result.challengeId;sentEmail.value=form.email;notice.value='验证码已就绪，5 分钟内有效。';}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function submit(){error.value='';notice.value='';if(form.password!==form.confirm){error.value='两次密码不一致';return;}if(!challenge.value||sentEmail.value!==form.email){error.value='请先获取当前邮箱的验证码';return;}busy.value=true;try{await realRequest(`/auth/${reset.value?'reset':'register'}`,{method:'POST',body:{...form,challengeId:challenge.value}});form.password=form.confirm=form.code='';clearRealSession();clearAccount();await router.replace({path:'/login',query:{notice:reset.value?'password-reset':'registered'}});}catch(e){error.value=e.message;}finally{busy.value=false;}}
</script>
<template><div class="page-heading"><div><p class="eyebrow">{{reset?'RECOVER YOUR ACCOUNT':'YOUR NEXT CHAPTER'}}</p><h1>{{reset?'找回密码':'注册账号'}}</h1><p class="muted">{{reset?'使用已绑定的邮箱设置新密码。':'创建自己的账户，保存简历、面试与成长记录。'}}</p></div></div>
<section class="card register-card"><p v-if="reset" class="small muted">尚未绑定邮箱的已有账号，请登录后绑定；若已忘记密码，请联系管理员。</p><form @submit.prevent="submit"><fieldset :disabled="busy"><template v-if="!reset"><label>昵称<input v-model="form.nickname" maxlength="20" required autocomplete="nickname"/></label><label>手机号<input v-model="form.phone" type="tel" pattern="1[0-9]{10}" maxlength="11" required autocomplete="username"/></label></template><label>{{reset?'已绑定邮箱':'邮箱'}}<input v-model="form.email" type="email" maxlength="254" required autocomplete="email"/></label><div class="code-row"><label>验证码<input v-model="form.code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required/></label><button type="button" class="button secondary" :disabled="!form.email" @click="send">获取验证码</button></div><label>新密码<input v-model="form.password" type="password" minlength="8" maxlength="72" autocomplete="new-password" required/></label><label>确认密码<input v-model="form.confirm" type="password" minlength="8" maxlength="72" autocomplete="new-password" required/></label><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p><button class="button primary wide">{{busy?'正在处理…':reset?'重置密码并重新登录':'创建账号'}}</button></fieldset></form><RouterLink to="/login" class="text-link">{{reset?'返回登录':'已有账号？立即登录'}}</RouterLink></section></template>
<style scoped>.register-card{max-width:620px;margin:24px auto}.register-card fieldset{border:0;margin:0;padding:0;min-width:0}.register-card label{margin:18px 0}.register-card>.text-link{display:inline-block;margin-top:18px}.code-row{display:flex;gap:12px;align-items:center}.code-row label{flex:1;min-width:0}.code-row button{flex-shrink:0;margin-top:24px}@media(max-width:450px){.code-row{align-items:stretch;flex-direction:column;gap:0}.code-row button{margin:0 0 12px}}</style>
