<script setup>
import { ref, reactive, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { realRequest, clearRealSession } from '../services/real.js';
import { logoutAccount, clearAccount } from '../services/realAccount.js';
const router=useRouter(),security=ref(null),error=ref(''),notice=ref(''),loading=ref(true),busy=ref(false),panel=ref(''),history=ref([]),historyLoaded=ref(false);
const form=reactive({email:'',currentPassword:'',password:'',confirm:'',code:''});
const challenge=ref(''),sentEmail=ref('');
const date=value=>value?new Date(Number(value)).toLocaleString():'尚无记录';
async function perform(fn){busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){error.value=e.message;if(e.status===401)await router.replace('/login?returnTo=/account');}finally{busy.value=false;}}
async function load(){loading.value=true;await perform(async()=>{security.value=await realRequest('/me/security');});loading.value=false;}
function choose(value){panel.value=panel.value===value?'':value;error.value='';notice.value='';Object.assign(form,{email:'',currentPassword:'',password:'',confirm:'',code:''});challenge.value='';}
async function send(){await perform(async()=>{challenge.value='';const result=await realRequest('/me/email/code',{method:'POST',body:{email:form.email,currentPassword:form.currentPassword}});challenge.value=result.challengeId;sentEmail.value=form.email;notice.value='验证码已就绪，5 分钟内有效。';});}
async function bind(){await perform(async()=>{if(!challenge.value||sentEmail.value!==form.email)throw Error('请先获取当前邮箱的验证码');security.value=await realRequest('/me/email',{method:'PUT',body:{currentPassword:form.currentPassword,challengeId:challenge.value,code:form.code}});choose('');notice.value='邮箱已保存（演示验证，未核实邮箱所有权）。';});}
async function password(){await perform(async()=>{if(form.password!==form.confirm)throw Error('两次新密码不一致');await realRequest('/me/password',{method:'PUT',body:{currentPassword:form.currentPassword,password:form.password}});clearRealSession();clearAccount();form.currentPassword=form.password=form.confirm='';await router.replace('/login?notice=password-reset');});}
async function showHistory(){choose('history');if(panel.value==='history')await perform(async()=>{historyLoaded.value=false;history.value=await realRequest('/me/login-history');historyLoaded.value=true;});}
async function logout(){await perform(async()=>{await logoutAccount();await router.replace('/login');});}
onMounted(load);
</script>
<template><div class="page-heading"><div><p class="eyebrow">ACCOUNT & SECURITY</p><h1>账户与安全</h1><p class="muted">管理登录方式、密码和账户安全。</p></div></div>
<p v-if="error" class="error" role="alert">{{error}} <button v-if="!security" class="text-link" @click="load">重新加载</button></p><p v-if="notice" class="notice" role="status">{{notice}}</p><section v-if="loading" class="card">正在读取账户信息…</section>
<template v-else-if="security"><div class="security-grid">
<section class="card"><h2>账户信息</h2><dl><div><dt>手机号</dt><dd>{{security.phone||'未提供'}}</dd></div><div><dt>绑定邮箱</dt><dd>{{security.email||'未绑定'}}</dd></div><div><dt>最近登录</dt><dd>{{date(security.lastLoginAt)}}</dd></div><div><dt>密码更新时间</dt><dd>{{date(security.passwordUpdatedAt)}}</dd></div></dl></section>
<section class="card"><h2>登录方式</h2><dl><div><dt>密码登录</dt><dd>已启用</dd></div><div><dt>手机验证码登录</dt><dd class="muted">{{security.smsLogin?'已启用':'未开放'}}</dd></div></dl><p class="small muted">使用手机号和密码登录；绑定邮箱用于找回密码。</p></section>
<section class="card"><h2>安全建议</h2><ul><li>本地演示请勿使用其他网站的真实密码。</li><li>修改或重置密码后，所有旧登录会失效。</li><li>在公共设备使用后及时退出登录。</li></ul></section>
<section class="card"><h2>安全操作</h2><div class="security-actions"><button :disabled="busy||!security.mailAvailable" @click="choose('email')">{{security.email?'更换绑定邮箱':'绑定邮箱'}} <span>›</span></button><button :disabled="busy" @click="choose('password')">修改密码 <span>›</span></button><RouterLink to="/forgot-password">忘记密码 / 邮箱重置 <span>›</span></RouterLink><button :disabled="busy" @click="showHistory">登录历史 <span>›</span></button></div></section></div>
<section v-if="panel" class="card security-panel"><div class="section-heading"><h2>{{panel==='email'?'绑定邮箱':panel==='password'?'修改密码':'登录历史'}}</h2><button class="text-link" :disabled="busy" @click="choose('')">收起</button></div>
<form v-if="panel==='email'" @submit.prevent="bind"><fieldset :disabled="busy"><label>当前密码<input v-model="form.currentPassword" type="password" autocomplete="current-password" required/></label><label>邮箱<input v-model="form.email" type="email" maxlength="254" required/></label><button type="button" class="button secondary" :disabled="!form.email||!form.currentPassword" @click="send">获取验证码</button><label>验证码<input v-model="form.code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required/></label><button class="button primary">保存绑定邮箱</button></fieldset></form>
<form v-if="panel==='password'" @submit.prevent="password"><fieldset :disabled="busy"><label>当前密码<input v-model="form.currentPassword" type="password" autocomplete="current-password" required/></label><label>新密码<input v-model="form.password" type="password" minlength="8" maxlength="72" autocomplete="new-password" required/><small class="muted">至少 8 位，最长 72 字节。</small></label><label>确认新密码<input v-model="form.confirm" type="password" minlength="8" maxlength="72" autocomplete="new-password" required/></label><p class="muted">保存后需要重新登录，其他设备的旧登录也会失效。</p><button class="button primary">更新密码并重新登录</button></fieldset></form>
<template v-if="panel==='history'"><p class="small muted">最近 50 次成功登录，使用服务端记录的时间和来源地址。</p><p v-if="!historyLoaded">{{busy?'正在读取…':'读取失败，请收起后重试。'}}</p><p v-else-if="!history.length" class="muted">暂无登录记录，下次成功登录后开始记录。</p><ul v-else class="history-list"><li v-for="(item,index) in history" :key="index"><strong>{{date(item.logged_at)}}</strong><span class="muted">{{item.address}} · 登录成功</span></li></ul></template></section>
<div class="security-footer"><button class="button secondary" :disabled="busy" @click="logout">{{busy?'正在处理…':'退出当前账号'}}</button></div></template></template>
<style scoped>.security-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.security-grid dl{margin:20px 0 0}.security-grid dl>div{display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line)}dt{color:var(--muted);flex-shrink:0}dd{margin:0;text-align:right;overflow-wrap:anywhere}dd small{display:block}.security-grid ul{padding-left:20px;line-height:2.4;margin-bottom:0}.security-footer{display:flex;justify-content:flex-end;margin-top:24px}.security-actions{margin-top:16px}.security-actions button,.security-actions a{display:flex;width:100%;justify-content:space-between;padding:12px 0;background:none;border:0;border-bottom:1px solid var(--line);text-align:left}.security-panel{margin-top:24px}.security-panel form{max-width:560px}.security-panel fieldset{border:0;padding:0;margin:0;min-width:0}.security-panel label{margin:18px 0}.history-list{list-style:none;padding:0}.history-list li{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:14px 0;border-bottom:1px solid var(--line)}@media(max-width:767px){.security-grid{grid-template-columns:1fr;gap:16px}.security-footer .button{width:100%}.history-list li{flex-direction:column}}</style>
