<script setup>
import { computed,ref } from 'vue';
import { useRoute,useRouter } from 'vue-router';
import { studio,dateLabel } from '../store.js';
import Chart from '../components/Chart.vue';
import SpeechPanel from '../components/SpeechPanel.vue';
import Icon from '../components/Icon.vue';
const route=useRoute(),router=useRouter(),tab=ref('overview'),selected=ref(0);
const s=computed(()=>studio.state.value.sessions.find(x=>x.id===route.params.sessionId));
const report=computed(()=>s.value?.report);
const speechReady=computed(()=>!s.value?.analysis||s.value.analysis.status==='completed');
const tabs=[['overview','总览'],['content','内容分析'],['speech','表达分析'],['reviews','逐题复盘'],['plan','提升计划']];
const dimensionNotes=['检查回答中的技术概念、方案和关键条件。','检查原理解释、边界条件和方案取舍。','检查结论、依据、步骤与验证是否连贯。','检查回答是否覆盖本岗位所需的能力点。'];
const evidence=computed(()=>report.value?.reviews[selected.value]||report.value?.reviews[0]);
function practice(topic){const p=studio.call('createPractice',s.value.id,topic);router.push(`/practice/${p.id}`)}
function exportReport(){const file=new Blob([JSON.stringify({label:'DEMO 演示报告',role:s.value.roleName,level:s.value.level,completedAt:s.value.completedAt,analysis:s.value.analysis,report:{...report.value,speech:speechReady.value?report.value.speech:{available:false,reason:'分析尚未完成'}}},null,2)],{type:'application/json'});const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=`面试报告-${s.value.roleId}-${s.value.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const prior=computed(()=>{const p=studio.state.value.plans.find(x=>x.id===s.value?.parentPlanId);const previous=studio.state.value.sessions.find(x=>x.id===p?.sessionId);const reviews=previous?.report?.reviews.filter(x=>x.topic===s.value.focusTopic)||[];return reviews.length?Math.round(reviews.reduce((n,x)=>n+x.score,0)/reviews.length):null});
</script>
<template><template v-if="report"><div class="page-heading report-heading"><div><p class="eyebrow">INTERVIEW REPORT</p><h1>看见表现，也看见下一步。</h1><p class="muted">{{s.roleName}} · {{s.level}} · {{dateLabel(s.completedAt)}} <span class="badge">{{s.seeded?'预置示例':'本次演示'}}报告</span></p></div><button class="text-link" @click="exportReport">导出报告 ↓</button></div>
<div v-if="!speechReady" class="notice">{{s.analysis.status==='failed'?'分析已中断':'分析尚未完成'}}，内容报告已保留。<RouterLink :to="`/interviews/${s.id}/analysis`" class="text-link">继续分析 →</RouterLink></div>
<section class="report-summary"><div class="summary-score"><Icon name="library"/><div><span>内容分析</span><strong>{{report.overall}}<small>/100</small></strong></div></div><div class="summary-score"><Icon name="mic"/><div><span>表达分析</span><strong v-if="report.speech.available&&speechReady">{{report.speech.score}}<small>/100 · 示例</small></strong><b v-else>{{speechReady?'未评估':'待完成'}}</b></div></div><div class="summary-copy"><strong>优先改进建议</strong><p>{{report.weaknesses[0]?.advice}}</p></div><button class="button primary" @click="practice(report.weaknesses[0]?.topic)">开始专项训练 <Icon name="right"/></button></section>
<p class="small muted">已回答 {{s.answers.length}} / {{s.questions.length}} 题{{s.answers.length<s.questions.length?' · 本次提前结束':''}} · 内容与表达分别展示，未评估项目不按 0 分计入。</p><p v-if="prior!==null" class="notice">同主题原得分 {{prior}} → 本次 {{report.overall}}。重复题目用于回顾表达变化，不代表能力提升证明。</p>
<div class="tabs report-tabs" role="tablist" aria-label="报告内容"><button v-for="[value,label] in tabs" :key="value" role="tab" :aria-selected="tab===value" :class="{active:tab===value}" @click="tab=value">{{label}}</button></div>
<div v-if="tab==='overview'" class="stack"><div class="two-col report-columns"><section class="card"><h2>内容分析</h2><p class="small muted">从技术、深度、逻辑与岗位匹配度，回顾回答质量。</p><Chart :values="report.dimensions.map(x=>x.value)" :labels="report.dimensions.map(x=>x.name)"/><div class="dimension-list"><span v-for="d in report.dimensions" :key="d.name">{{d.name}} <b>{{d.value}}</b></span></div><div class="reference report-evidence"><h3>回答依据 · {{evidence.topic}}</h3><p class="quote">「{{evidence.text}}」</p><p>{{evidence.advice}}</p><button class="text-link" @click="tab='content'">查看四维分析与依据 →</button></div></section><section class="card"><template v-if="report.speech.available&&speechReady"><span class="badge">示例音频与分析</span><h2>表达分析</h2><div class="speech-metrics"><div><span>语速</span><strong>{{report.speech.clips[0].speed}}<small> 字/分钟</small></strong></div><div><span>清晰度</span><strong>良好<small>（示例）</small></strong></div><div><span>表达自信度</span><strong>估计</strong></div></div><p class="notice">表达分与清晰度、自信度为预设示例，并非对你的声学或心理状态的判断。</p><h3>{{report.speech.clips[0].topic}} · 示例回放</h3><audio controls :src="report.speech.clips[0].file" preload="metadata" aria-label="报告示例音频"/><p>先给结论，再分点解释依据；在观点之间有意识地停顿。</p><button class="button secondary" @click="tab='speech'">查看表达分析 →</button></template><template v-else><h2>表达分析</h2><p>{{speechReady?report.speech.reason:'完成分析流程后展示表达分析状态。'}}</p><p class="notice">纯文字回答不会生成语速、清晰度或自信度分数。</p><RouterLink :to="`/interviews/new?role=${s.roleId}`" class="button secondary">新建面试，体验示例音频 →</RouterLink></template></section></div><section class="card sage"><h2>亮点与不足</h2><div class="findings-grid"><div><h3>主要亮点</h3><p>{{report.reviews.slice().sort((a,b)=>b.score-a.score)[0]?.highlight}}</p></div><div><h3>待改进</h3><p>{{report.weaknesses[0]?.advice}}</p></div><div><h3>下一步建议</h3><p>阅读知识要点，重写回答，再做同主题练习。</p><button class="text-link" @click="tab='plan'">查看提升计划 →</button></div></div></section></div>
<section v-else-if="tab==='content'" class="card"><h2>四个维度，都有回答依据。</h2><p class="notice">本轮使用 {{report.rubricVersion}} 本地规则。分数由关键词覆盖和文本长度映射，不是实际大模型深度评价。</p><div class="dimension-cards"><article v-for="(d,i) in report.dimensions" :key="d.name"><span>{{d.name}}</span><strong>{{d.value}}<small>/100</small></strong><p>{{dimensionNotes[i]}}</p><p class="small muted">演示评分口径：{{i===0?'关键词命中与回答长度':i===1?'关键词覆盖映射':i===2?'文本长度映射，不能代表真实逻辑水平':'岗位题目关键词覆盖映射'}}</p></article></div><label>选择回答查看依据<select v-model="selected"><option v-for="(r,i) in report.reviews" :key="r.questionId" :value="i">第 {{i+1}} 题 · {{r.topic}}</option></select></label><div v-if="evidence" class="two-col"><article><h3>{{evidence.question}}</h3><p class="answer-review preserve">{{evidence.text}}</p><div class="tags"><span v-for="hit in evidence.hits" :key="hit">已覆盖：{{hit}}</span><span v-for="miss in evidence.missing" :key="miss">待补充：{{miss}}</span></div></article><article class="reference"><h3>亮点与不足</h3><p>{{evidence.highlight}}</p><p>{{evidence.advice}}</p><h3>参考思路</h3><p>{{evidence.reference}}</p><button class="text-link" @click="tab='plan'">进入提升计划 →</button></article></div></section>
<section v-else-if="tab==='speech'" class="card"><SpeechPanel v-if="speechReady" :speech="report.speech"/><div v-else class="empty"><h2>表达分析尚未完成</h2><RouterLink :to="`/interviews/${s.id}/analysis`">继续或重试分析 →</RouterLink></div></section>
<div v-else-if="tab==='reviews'" class="stack"><article v-for="(r,i) in report.reviews" :key="r.questionId" class="card review-card"><div class="section-heading"><span class="eyebrow">QUESTION {{i+1}} / {{r.stage}}</span><span class="badge">{{r.score}} 分 · 演示</span></div><h2>{{r.question}}</h2><h3>你的回答{{r.audioSampleId?'（基于示例转写）':''}}</h3><p class="answer-review preserve">{{r.text}}</p><details v-if="r.originalTranscript"><summary>查看音频原始转写，保留编辑前依据</summary><p>{{r.originalTranscript}}</p></details><div class="two-col"><div><h3>回答反馈</h3><p>{{r.highlight}}</p><p>{{r.advice}}</p></div><div class="reference"><h3>参考思路</h3><p>{{r.reference}}</p></div></div></article></div>
<section v-else class="card"><h2>把建议，变成一次具体练习。</h2><article v-for="w in report.weaknesses" :key="w.topic" class="list-row"><div><h3>{{w.topic}}</h3><p>{{w.advice}}</p><p class="small muted">阅读要点 → 重写回答 → 专项再测</p></div><button class="button primary" @click="practice(w.topic)">开始练习 →</button></article><div class="reference"><h3>表达练习</h3><p>先写一句结论，再用两点依据展开。可以在新面试中体验示例音频流程；当前不采集或评估真实录音。</p><RouterLink :to="`/interviews/new?role=${s.roleId}`" class="text-link">开始新的面试 →</RouterLink></div></section>
<p class="notice">评分来源为 Mock：内容由本地规则计算，表达仅针对关联的合成示例展示预设结果。所有结果用于产品流程演示。</p></template><section v-else class="card empty"><h1>报告尚未生成</h1><p>完成至少一道题并结束面试后，即可查看报告。</p><RouterLink :to="s?`/interviews/${s.id}/plan`:'/interviews'">返回面试</RouterLink></section></template>
