<script setup>
import { ref } from 'vue';
defineProps({speech:Object});
const failed=ref({});
const players={};const stopAt={};
function playExcerpt(id,duration){const player=players[id];if(!player)return;Object.values(players).forEach(p=>p?.pause());player.currentTime=0;stopAt[id]=Math.min(6,duration);player.play().catch(()=>{failed.value[id]=true});}
function tick(id){if(stopAt[id]&&players[id]?.currentTime>=stopAt[id]){players[id].pause();delete stopAt[id];}}


</script>
<template><section v-if="speech.available" class="speech-panel"><span class="badge">示例音频 · 预设表达分析</span><h2>表达分析</h2><p class="muted small">合成示例的展示结果，与用户的真实表达能力无关。</p><div class="speech-metrics"><div><span>语速</span><strong>{{speech.clips[0].speed}}<small> 字/分钟</small></strong></div><div><span>清晰度</span><strong>良好<small>（示例）</small></strong></div><div><span>表达自信度</span><strong>较稳定<small>（估计）</small></strong></div></div><p class="notice">语速按示例文稿字符数和音频时长计算；清晰度、自信度与表达分为预设演示值，不代表真实心理状态。</p><details v-if="speech.fallback?.isMock" class="notice"><summary>Mock 兜底字段（示例，不计入真实成长统计）</summary><p>以下为真实表达服务未接入时的固定占位结果；上方语速仍来自示例音频计算。</p><p v-for="(field,key) in speech.fallback.fields" :key="key"><strong>{{field.label}}：</strong>{{field.value ?? '未评估'}} {{field.unit}} · {{field.source==='mock'?'Mock 示例':field.source==='real'?'真实结果':'未评估'}}</p></details><h3>音频片段时间线</h3><p class="small muted">每段对应已提交的示例回答，点击回放前 6 秒；长度按实际音频时长展示。</p><div class="audio-timeline"><button v-for="(clip,i) in speech.clips" :key="clip.questionId" :style="{flex:clip.duration}" @click="playExcerpt(clip.questionId,clip.duration)">片段 {{i+1}}<small>{{clip.duration}} 秒</small></button></div><article v-for="(clip,i) in speech.clips" :key="clip.questionId" class="speech-clip"><div class="section-heading"><h3>第 {{i+1}} 段 · {{clip.topic}}</h3><span class="small muted">{{clip.duration}} 秒</span></div><audio :ref="el=>players[clip.questionId]=el" @timeupdate="tick(clip.questionId)" controls preload="metadata" :src="clip.file" :aria-label="clip.topic+'示例音频'" @error="failed[clip.questionId]=true"/><p v-if="failed[clip.questionId]" class="error" role="status">示例音频加载失败，请刷新后重试。以下文字仍可查看。</p><details><summary>查看原始示例转写</summary><p>{{clip.text}}</p></details><div class="reference"><b>练习建议</b><p>先用一句话说结论，再分点解释依据；在观点之间有意识地停顿。</p></div></article></section><section v-else class="empty"><h2>本次表达表现未评估</h2><p>{{speech.reason}}</p><p class="small muted">没有有效音频时不显示表达分，也不将其计为 0 分。</p></section></template>
