import test from 'node:test';
import assert from 'node:assert/strict';
import { createDemoService, STORAGE_KEY } from './demo.js';
import { roles } from './roles.js';
import { audioSamples } from './audioSamples.js';
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),data}};
function setup(storage=memory()){let n=0;return {storage,api:createDemoService({storage,seed:false,id:()=>`test-${++n}`,now:()=> '2026-09-21T10:00:00.000Z'})}}
function complete(api,s){api.startSession(s.id);while(s.status!=='completed'){const q=s.questions[s.answers.length];s=api.submitAnswer(s.id,{questionId:q.id,text:q.sample})}return s}
for(const role of roles)test(`${role.title}: prepare → plan → interview → report → practice → retest`,()=>{
 const {api}=setup();let s=api.createSession({roleId:role.id,level:'初级',resumeMode:'skip'});assert.equal(s.status,'ready');assert.equal(s.questions.length,4);assert.equal(s.context.resume,'');assert.ok(s.questions.every(q=>role.questions.some(original=>original.id===q.id)));
 s=complete(api,s);assert.equal(s.answers.length,5);assert.equal(s.questions.filter(q=>q.isFollowup).length,1);assert.ok(s.report.overall>=42);assert.equal(s.report.speech.available,false);
 const p=api.createPractice(s.id,s.report.weaknesses[0].topic);assert.equal(api.createPractice(s.id,p.topic).id,p.id);assert.throws(()=>api.startRetest(p.id));api.updatePractice(p.id,{steps:[true,true,true],draft:'我会根据场景说明判断依据，补充具体方案和验证方式。'});
 let retest=api.startRetest(p.id);assert.equal(retest.roleId,role.id);assert.equal(retest.level,'初级');assert.equal(retest.parentPlanId,p.id);assert.equal(retest.questions.length,1);assert.equal(api.startRetest(p.id).id,retest.id);retest=complete(api,retest);assert.equal(retest.answers.length,2);assert.equal(api.snapshot().sessions.length,2);
});
test('draft, paused progress, plans and report survive refresh without cross-role changes',()=>{
 const {api,storage}=setup();const a=api.createSession({roleId:'algorithm'}),b=api.createSession({roleId:'testing'});api.startSession(a.id);api.saveDraft(a.id,'需要保留的算法面试草稿');api.pauseSession(a.id);const restored=createDemoService({storage});assert.equal(restored.getSession(a.id).draft,'需要保留的算法面试草稿');assert.equal(restored.getSession(a.id).status,'paused');assert.equal(restored.getSession(b.id).answers.length,0);assert.equal(restored.getSession(b.id).status,'ready');
});
test('stale duplicate answer and invalid inputs cannot mutate progress',()=>{const {api}=setup();const s=api.createSession({roleId:'java'});const q=s.questions[0];assert.throws(()=>api.submitAnswer(s.id,{questionId:q.id,text:'短'}));assert.equal(api.getSession(s.id).answers.length,0);api.submitAnswer(s.id,{questionId:q.id,text:q.sample});assert.throws(()=>api.submitAnswer(s.id,{questionId:q.id,text:q.sample}));assert.equal(api.getSession(s.id).answers.length,1);assert.throws(()=>api.createSession({roleId:'unknown'}));assert.throws(()=>api.createSession({roleId:'java',focusTopic:'数据泄漏'}));});
test('partial completion evaluates submitted answers only and is immutable',()=>{const {api}=setup();let s=api.createSession({roleId:'web'});assert.throws(()=>api.finishSession(s.id));s=api.submitAnswer(s.id,{questionId:s.questions[0].id,text:s.questions[0].sample,inputType:'demo-voice'});s=api.finishSession(s.id);assert.equal(s.report.reviews.length,1);assert.equal(s.report.speech.available,false);assert.match(s.report.speech.reason,/示例转写/);assert.throws(()=>api.submitAnswer(s.id,{questionId:s.questions[1].id,text:'不能提交已完成的会话'}));assert.equal(api.startSession(s.id).status,'completed');});
test('corrupt storage recovers visibly; quota failure stays usable; reset only owns its key',()=>{const storage=memory();storage.setItem('app_auth_token','untouched');storage.setItem(STORAGE_KEY,'broken');const api=createDemoService({storage,seed:false});assert.match(api.snapshot().warning,/无法读取/);api.createSession({roleId:'testing'});api.reset();assert.equal(api.snapshot().sessions.length,0);assert.equal(storage.getItem('app_auth_token'),'untouched');const limited=createDemoService({storage:{getItem:()=>null,setItem:()=>{throw Error('quota')}},seed:false});assert.match(limited.snapshot().warning,/空间不足/);assert.equal(limited.createSession({roleId:'java'}).status,'ready');});
test('seeds cover all roles, are labelled, and cannot mutate service through snapshots',()=>{const api=createDemoService({storage:memory()});for(const role of roles)assert.equal(api.snapshot().sessions.filter(s=>s.roleId===role.id&&s.status==='completed'&&s.seeded).length,3);const snapshot=api.snapshot();snapshot.sessions[0].answers=[];assert.equal(api.snapshot().sessions[0].answers.length,1);});
test('demo voice provenance survives saving a draft and reopening',()=>{const {api,storage}=setup();const s=api.createSession({roleId:'testing'});api.saveDraft(s.id,'示例转写文本需要保留来源，不能被标记为真实录音。','demo-voice');const restored=createDemoService({storage});assert.equal(restored.getSession(s.id).draftInputType,'demo-voice');});
test('partially damaged records recover instead of crashing report views',()=>{const {api,storage}=setup();const s=complete(api,api.createSession({roleId:'java'}));const raw=JSON.parse(storage.getItem(STORAGE_KEY));delete raw.sessions[0].context;storage.setItem(STORAGE_KEY,JSON.stringify(raw));const restored=createDemoService({storage,seed:false});assert.match(restored.snapshot().warning,/无法读取/);assert.equal(restored.snapshot().sessions.length,0);});
for(const role of roles)test(`${role.name}: audio confirmation → report → analysis retry`,()=>{const {api,storage}=setup();let s=api.createSession({roleId:role.id});const clip=audioSamples.find(a=>a.roleId===role.id);api.setInputMode(s.id,'demo-audio');api.saveDraft(s.id,clip.text,'demo-voice',clip.id);const restored=createDemoService({storage});assert.equal(restored.getSession(s.id).draftAudioSampleId,clip.id);s=restored.submitAnswer(s.id,{questionId:s.questions[0].id,text:clip.text+' 我还补充了验证方法。',inputType:'demo-voice',audioSampleId:clip.id});s=restored.finishSession(s.id);assert.equal(s.report.speech.available,true);assert.equal(s.report.speech.source,'demo-audio');assert.equal(s.report.reviews[0].originalTranscript,clip.text);assert.equal(s.analysis.status,'pending');restored.advanceAnalysis(s.id);restored.failAnalysis(s.id);assert.equal(restored.getSession(s.id).analysis.status,'failed');restored.retryAnalysis(s.id);restored.advanceAnalysis(s.id);restored.advanceAnalysis(s.id);assert.equal(restored.getSession(s.id).analysis.status,'completed');assert.equal(restored.getSession(s.id).answers.length,1);});
test('audio from a different role is rejected without saving an answer',()=>{const {api}=setup();const s=api.createSession({roleId:'java'});const clip=audioSamples.find(a=>a.roleId==='web');assert.throws(()=>api.submitAnswer(s.id,{questionId:s.questions[0].id,text:clip.text,inputType:'demo-voice',audioSampleId:clip.id}),/岗位不匹配/);assert.equal(api.getSession(s.id).answers.length,0);});
